services:
    acme.demo.controller:
        class: andreask\giphyforphpbb\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@user'
    andreask.giphyforphpbb.listener:
        class: andreask\giphyforphpbb\event\main_listener
        arguments:
            - '@config_text'
            - '@template'
            - '@language'
        tags:
            - { name: event.listener }
